// Nutrition product database with carb, sodium, and water values
export type NutritionCategory =
  | "Gels"
  | "Drinks"
  | "Electrolytes"
  | "Bars"
  | "Real Food"
  | "Other";

export interface NutritionProduct {
  name: string;
  defaultCarbs: number; // grams of carbohydrates
  defaultSodium: number; // mg of sodium
  defaultWater: number; // ml of water
  defaultCaffeine?: number; // mg of caffeine (optional)
  servingSize: string;
  category: NutritionCategory;
}

export const NUTRITION_DATABASE: NutritionProduct[] = [
  // ========== GELS (13 products) ==========
  {
    name: "Active Root Sports Drink Mix",
    defaultCarbs: 40,
    defaultSodium: 226,
    defaultWater: 0,
    servingSize: "gel",
    category: "Gels",
  },
  {
    name: "Active Root Energy Gel",
    defaultCarbs: 30,
    defaultSodium: 40,
    defaultWater: 0,
    servingSize: "42 Grams",
    category: "Gels",
  },
  {
    name: "Active Root Energy Gel Mix",
    defaultCarbs: 24.3,
    defaultSodium: 40,
    defaultWater: 0,
    servingSize: "25 Grams",
    category: "Gels",
  },
  {
    name: "Active Root Guarana (Caffeinated) Energy Gel Mix",
    defaultCarbs: 24.3,
    defaultSodium: 40,
    defaultWater: 0,
    defaultCaffeine: 75,
    servingSize: "25 Gram Serving",
    category: "Gels",
  },
  {
    name: "Maurten",
    defaultCarbs: 25,
    defaultSodium: 50,
    defaultWater: 0,
    servingSize: "gel",
    category: "Gels",
  },
  {
    name: "SIS Go Isotonic",
    defaultCarbs: 22,
    defaultSodium: 55,
    defaultWater: 0,
    servingSize: "gel",
    category: "Gels",
  },
  {
    name: "High 5",
    defaultCarbs: 23,
    defaultSodium: 30,
    defaultWater: 0,
    servingSize: "gel",
    category: "Gels",
  },
  {
    name: "GU Energy",
    defaultCarbs: 22,
    defaultSodium: 55,
    defaultWater: 0,
    servingSize: "gel",
    category: "Gels",
  },
  {
    name: "Cliff Shot Bloks",
    defaultCarbs: 24,
    defaultSodium: 70,
    defaultWater: 0,
    servingSize: "3 blocks",
    category: "Gels",
  },
  {
    name: "PF 30 Gel",
    defaultCarbs: 30,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "51 Grams",
    category: "Gels",
  },
  {
    name: "PF 30 Caffeine 100mg Gel",
    defaultCarbs: 30,
    defaultSodium: 0,
    defaultWater: 0,
    defaultCaffeine: 100,
    servingSize: "51 Grams",
    category: "Gels",
  },
  {
    name: "PF 90 Gel ( Jumbo Gel )",
    defaultCarbs: 90,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "153 Grams",
    category: "Gels",
  },
  {
    name: "PF 300 Flow Gel",
    defaultCarbs: 300,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "510 Grams",
    category: "Gels",
  },

  // ========== DRINKS (17 products) ==========
  {
    name: "Active Root Sports Drink Mix - Caffeinated",
    defaultCarbs: 40,
    defaultSodium: 227,
    defaultWater: 0,
    defaultCaffeine: 75,
    servingSize: "42 Grams ( Pouch )",
    category: "Drinks",
  },
  {
    name: "Active Root Recovery Drink Mix",
    defaultCarbs: 32.6,
    defaultSodium: 188,
    defaultWater: 0,
    servingSize: "35 Gram Serving",
    category: "Drinks",
  },
  {
    name: "Tailwind Endurance Fuel",
    defaultCarbs: 25,
    defaultSodium: 310,
    defaultWater: 500,
    servingSize: "27g (590 - 710ml)",
    category: "Drinks",
  },
  {
    name: "Tailwind High Carb Fuel",
    defaultCarbs: 90,
    defaultSodium: 680,
    defaultWater: 500,
    servingSize: "92g (475-710ml)",
    category: "Drinks",
  },
  {
    name: "Tailwind Recovery Mix",
    defaultCarbs: 34,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "60 Grams ( 3 Scoops )",
    category: "Drinks",
  },
  {
    name: "CNP Cyclic Dextrin",
    defaultCarbs: 49,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "50 Grams",
    category: "Drinks",
  },
  {
    name: "My Protein Maltodextrin Carbs",
    defaultCarbs: 48,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "59 Grams Serving",
    category: "Drinks",
  },
  {
    name: "Bulk  Dextrose (Glucose Powder)",
    defaultCarbs: 23,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "25 Gram Serving",
    category: "Drinks",
  },
  {
    name: "Optimum Nutrition GOLD STANDARD 100% Whey Protein",
    defaultCarbs: 1.6,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "31 Grams Serving",
    category: "Drinks",
  },
  {
    name: "Bulk Supplements Organic Lemon Powder",
    defaultCarbs: 0,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "450 mg per 237 ml to 355 ml water",
    category: "Drinks",
  },
  {
    name: "Carb Only Drink Mix",
    defaultCarbs: 30,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "2 Scoops",
    category: "Drinks",
  },
  {
    name: "Carb & Electrolyte Drink Mix",
    defaultCarbs: 30,
    defaultSodium: 250,
    defaultWater: 0,
    servingSize: "2 Scoops",
    category: "Drinks",
  },
  {
    name: "SIS Go Electrolyte",
    defaultCarbs: 36,
    defaultSodium: 345,
    defaultWater: 500,
    servingSize: "powder (500ml)",
    category: "Drinks",
  },
  {
    name: "Coke",
    defaultCarbs: 27,
    defaultSodium: 45,
    defaultWater: 330,
    defaultCaffeine: 34,
    servingSize: "can (330ml)",
    category: "Drinks",
  },
  {
    name: "Gatorade",
    defaultCarbs: 14,
    defaultSodium: 110,
    defaultWater: 240,
    servingSize: "bottle (240ml)",
    category: "Drinks",
  },
  {
    name: "Yazoo Chocolate Milkshake Drink",
    defaultCarbs: 35.2,
    defaultSodium: 0.1,
    defaultWater: 0,
    servingSize: "400ml",
    category: "Drinks",
  },
  {
    name: "Water",
    defaultCarbs: 0,
    defaultSodium: 0,
    defaultWater: 500,
    servingSize: "bottle (500ml)",
    category: "Drinks",
  },

  // ========== ELECTROLYTES (10 products) ==========
  {
    name: "Precision Hydration 500",
    defaultCarbs: 0,
    defaultSodium: 250,
    defaultWater: 500,
    servingSize: "tablet (500ml)",
    category: "Electrolytes",
  },
  {
    name: "Precision Hydration 1000",
    defaultCarbs: 0,
    defaultSodium: 500,
    defaultWater: 500,
    servingSize: "tablet (500ml)",
    category: "Electrolytes",
  },
  {
    name: "Precision Hydration 1500",
    defaultCarbs: 0,
    defaultSodium: 750,
    defaultWater: 500,
    servingSize: "tablet (500ml)",
    category: "Electrolytes",
  },
  {
    name: "Nuun Sport",
    defaultCarbs: 4,
    defaultSodium: 300,
    defaultWater: 500,
    servingSize: "tablet (500ml)",
    category: "Electrolytes",
  },
  {
    name: "HIGH5 ZERO Electrolyte Tablet",
    defaultCarbs: 0,
    defaultSodium: 250,
    defaultWater: 750,
    servingSize: "tablet (750ml)",
    category: "Electrolytes",
  },
  {
    name: "Salt Capsule (S!Caps)",
    defaultCarbs: 0,
    defaultSodium: 341,
    defaultWater: 0,
    servingSize: "capsule",
    category: "Electrolytes",
  },
  {
    name: "Salt Stick",
    defaultCarbs: 0,
    defaultSodium: 215,
    defaultWater: 0,
    servingSize: "capsule",
    category: "Electrolytes",
  },
  {
    name: "LMNT Zero-Sugar Electrolytes",
    defaultCarbs: 0,
    defaultSodium: 1000,
    defaultWater: 0,
    servingSize: "6 Grams",
    category: "Electrolytes",
  },
  {
    name: "Bulk Sodium Chloride (Table Salt)",
    defaultCarbs: 0,
    defaultSodium: 387,
    defaultWater: 0,
    servingSize: "1 Gram",
    category: "Electrolytes",
  },
  {
    name: "Slow-Sodium (Slow Release Sodium Tablets)",
    defaultCarbs: 0,
    defaultSodium: 600,
    defaultWater: 0,
    servingSize: "x1 Tablet",
    category: "Electrolytes",
  },

  // ========== BARS (12 products) ==========
  {
    name: "PF 60 Energy Chew Bar",
    defaultCarbs: 60,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "68g",
    category: "Bars",
  },
  {
    name: "Active Root Energy Chews",
    defaultCarbs: 24,
    defaultSodium: 58,
    defaultWater: 0,
    servingSize: "Per 32g Serving (5 Energy Chews)",
    category: "Bars",
  },
  {
    name: "PF 30 Chew",
    defaultCarbs: 30,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "34 Grams",
    category: "Bars",
  },
  {
    name: "PF 60 Chew Bar",
    defaultCarbs: 60,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "68 Grams",
    category: "Bars",
  },
  {
    name: "Nâak",
    defaultCarbs: 35,
    defaultSodium: 180,
    defaultWater: 0,
    servingSize: "waffle",
    category: "Bars",
  },
  {
    name: "Clif Bar",
    defaultCarbs: 45,
    defaultSodium: 200,
    defaultWater: 0,
    servingSize: "bar",
    category: "Bars",
  },
  {
    name: "TREK Cocoa Oat Protein Flapjack",
    defaultCarbs: 21.9,
    defaultSodium: 0.5,
    defaultWater: 0,
    servingSize: "50g",
    category: "Bars",
  },
  {
    name: "Stoats Apple & Cinnamon Porridge Oat Bar",
    defaultCarbs: 26.6,
    defaultSodium: 0.5,
    defaultWater: 0,
    servingSize: "50g",
    category: "Bars",
  },
  {
    name: "Stoats Classic Scottish Porridge Pot",
    defaultCarbs: 35.4,
    defaultSodium: 0.22,
    defaultWater: 0,
    servingSize: "60g",
    category: "Bars",
  },
  {
    name: "KIND Caramel Almond & Sea Salt",
    defaultCarbs: 16,
    defaultSodium: 125,
    defaultWater: 0,
    servingSize: "40g",
    category: "Bars",
  },
  {
    name: "Nature Valley Crunchy Oats & Honey",
    defaultCarbs: 26,
    defaultSodium: 160,
    defaultWater: 0,
    servingSize: "42g (2 bars)",
    category: "Bars",
  },
  {
    name: "Nakd Cocoa Orange",
    defaultCarbs: 23,
    defaultSodium: 5,
    defaultWater: 0,
    servingSize: "35g",
    category: "Bars",
  },

  // ========== REAL FOOD (8 products) ==========
  {
    name: "Pure Clear Honey",
    defaultCarbs: 12,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "1 Tablespoon",
    category: "Real Food",
  },
  {
    name: "Banana",
    defaultCarbs: 27,
    defaultSodium: 1,
    defaultWater: 0,
    servingSize: "medium",
    category: "Real Food",
  },
  {
    name: "White Bread Thick White Warburtons",
    defaultCarbs: 22,
    defaultSodium: 0.46,
    defaultWater: 0,
    servingSize: "1 slice (40g)",
    category: "Real Food",
  },
  {
    name: "Jam Strawberry",
    defaultCarbs: 14,
    defaultSodium: 0.46,
    defaultWater: 0,
    servingSize: "1 tablespoon (20g)",
    category: "Real Food",
  },
  {
    name: "Almond Butter Pip and Nut",
    defaultCarbs: 0,
    defaultSodium: 0.46,
    defaultWater: 0,
    servingSize: "1 tablespoon (20g)",
    category: "Real Food",
  },
  {
    name: "Ambrosia Rice Pudding",
    defaultCarbs: 19.1,
    defaultSodium: 1,
    defaultWater: 0,
    servingSize: "120g",
    category: "Real Food",
  },
  {
    name: "Ambrosia Ready To Eat Devon Custard",
    defaultCarbs: 17.8,
    defaultSodium: 1,
    defaultWater: 0,
    servingSize: "120g",
    category: "Real Food",
  },
  {
    name: "Boiled Potatoes (small)",
    defaultCarbs: 15,
    defaultSodium: 5,
    defaultWater: 0,
    servingSize: "100g",
    category: "Real Food",
  },

  // ========== OTHER (4 products) ==========
  {
    name: "Jelly Babies",
    defaultCarbs: 5,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "x1",
    category: "Other",
  },
  {
    name: "My Protein Unflavoured Impact BCAA",
    defaultCarbs: 0,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "5 Grams",
    category: "Other",
  },
  {
    name: "Caffeine Tablet/Gel",
    defaultCarbs: 0,
    defaultSodium: 0,
    defaultWater: 0,
    defaultCaffeine: 100,
    servingSize: "tablet/gel",
    category: "Other",
  },
  {
    name: "Drop Bag",
    defaultCarbs: 0,
    defaultSodium: 0,
    defaultWater: 0,
    servingSize: "n/a",
    category: "Other",
  },
];
