export const MANDATORY_KIT_ITEMS = [
  'Event bib number',
  'Identification',
  'Emergency cash',
  'Mobile phone (fully charged)',
  'Waterproof jacket (taped)',
  'Insulated mid-layer jacket',
  'Waterproof trousers (taped)',
  'Waterproof overtrousers (taped)',
  'Warm base layers (synthetic or merino wool)',
  'Warm hat/beanie',
  'Spare socks',
  'Spare running shoes',
  'Gloves',
  'Gaiters (for muddy conditions)',
  'Head torch with spare batteries',
  'Reflective clothing',
  'Reflective Red LED',
  'Emergency bivvy bag',
  'Foil blanket',
  'Small emergency blanket',
  'Emergency shelter (space blanket)',
  'Personal medication (NO NSAID)',
  'Electrolyte tablets',
  'Extra food for weather delays',
  'Compression bandages',
  'Water purification tablets or filter',
  'First aid kit (basic supplies, sterile needles, alcohol swabs, blisters and cuts)',
  'Anti chafing kit',
  'Sun protection (hat, sunglasses, sunscreen)',
  'Insect repellent',
  'Whistle',
  'Map and compass',
  'GPS device',
  'Food and drink',
  'Knife or multi-tool',
  'Trekking poles',
  'Insulated sleeping pad',
  'Duct tape (for repairs)',
] as const;

export const KIT_CATEGORIES = {
  'Essential Items': [
    'Event bib number',
    'Identification',
    'Emergency cash',
    'Mobile phone (fully charged)',
  ],
  'Clothing & Protection': [
    'Waterproof jacket (taped)',
    'Insulated mid-layer jacket',
    'Waterproof trousers (taped)',
    'Waterproof overtrousers (taped)',
    'Warm base layers (synthetic or merino wool)',
    'Warm hat/beanie',
    'Spare socks',
    'Spare running shoes',
    'Gloves',
    'Gaiters (for muddy conditions)',
    'Reflective clothing',
    'Reflective Red LED',
    'Sun protection (hat, sunglasses, sunscreen)',
  ],
  'Safety & Emergency': [
    'Head torch with spare batteries',
    'Emergency bivvy bag',
    'Foil blanket',
    'Small emergency blanket',
    'Emergency shelter (space blanket)',
    'Whistle',
    'Insect repellent',
  ],
  'Navigation': [
    'Map and compass',
    'GPS device',
  ],
  'Medical & First Aid': [
    'Personal medication (NO NSAID)',
    'First aid kit (basic supplies, sterile needles, alcohol swabs, blisters and cuts)',
    'Anti chafing kit',
    'Compression bandages',
  ],
  'Nutrition & Hydration': [
    'Food and drink',
    'Electrolyte tablets',
    'Extra food for weather delays',
    'Water purification tablets or filter',
  ],
  'Tools & Accessories': [
    'Knife or multi-tool',
    'Trekking poles',
    'Insulated sleeping pad',
    'Duct tape (for repairs)',
  ],
};

export const KIT_PRESETS: Record<string, string[]> = {
  'Summer Ultra': [
    'Event bib number',
    'Identification',
    'Emergency cash',
    'Mobile phone (fully charged)',
    'Waterproof jacket (taped)',
    'Head torch with spare batteries',
    'Whistle',
    'Map and compass',
    'Food and drink',
    'Sun protection (hat, sunglasses, sunscreen)',
  ],
  'Winter Ultra': [
    'Event bib number',
    'Identification',
    'Emergency cash',
    'Mobile phone (fully charged)',
    'Waterproof jacket (taped)',
    'Insulated mid-layer jacket',
    'Waterproof trousers (taped)',
    'Warm base layers (synthetic or merino wool)',
    'Warm hat/beanie',
    'Gloves',
    'Head torch with spare batteries',
    'Emergency bivvy bag',
    'Foil blanket',
    'Whistle',
    'Map and compass',
    'GPS device',
    'Food and drink',
  ],
  'Mountain Race': [
    'Event bib number',
    'Identification',
    'Emergency cash',
    'Mobile phone (fully charged)',
    'Waterproof jacket (taped)',
    'Warm hat/beanie',
    'Gloves',
    'Head torch with spare batteries',
    'Emergency bivvy bag',
    'Foil blanket',
    'Whistle',
    'Map and compass',
    'GPS device',
    'Food and drink',
    'Trekking poles',
  ],
  '100 Miler': [
    'Event bib number',
    'Identification',
    'Emergency cash',
    'Mobile phone (fully charged)',
    'Waterproof jacket (taped)',
    'Warm hat/beanie',
    'Spare socks',
    'Spare running shoes',
    'Gloves',
    'Head torch with spare batteries',
    'Reflective clothing',
    'Emergency bivvy bag',
    'Whistle',
    'Map and compass',
    'GPS device',
    'Food and drink',
    'Anti chafing kit',
    'First aid kit (basic supplies, sterile needles, alcohol swabs, blisters and cuts)',
    'Trekking poles',
  ],
};
